"""Add major and graduation_year to User

Revision ID: 1373a17ac3c0
Revises: 985802f1e2d4
Create Date: 2025-11-05 16:14:26.112121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1373a17ac3c0'
down_revision: Union[str, Sequence[str], None] = '985802f1e2d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'major',
               existing_type=sa.String(),
               nullable=False)
    op.alter_column('user', 'graduation_year',
               existing_type=sa.Integer(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'graduation_year',
               existing_type=sa.NullType(),
               nullable=True)
    op.alter_column('user', 'major',
               existing_type=sa.NullType(),
               nullable=True)
    # ### end Alembic commands ###
