"""Models edited

Revision ID: 1488b712c39c
Revises: a52304c4ad30
Create Date: 2025-12-30 23:18:40.314221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1488b712c39c'
down_revision: Union[str, Sequence[str], None] = 'a52304c4ad30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Drop temp table if it exists (from previous failed migration)
    conn = op.get_bind()
    try:
        conn.execute(sa.text("DROP TABLE IF EXISTS _alembic_tmp_lostandfounditem"))
        conn.execute(sa.text("DROP TABLE IF EXISTS _alembic_tmp_prayerrequest"))
    except Exception:
        pass  # Ignore if tables don't exist
    
    # First, set a default user_id for existing rows that have NULL
    # Get the first user ID (preferably admin, otherwise first user)
    result = conn.execute(sa.text("SELECT id FROM userbase WHERE is_admin = 1 LIMIT 1"))
    admin_user = result.fetchone()
    if admin_user:
        default_user_id = admin_user[0]
    else:
        result = conn.execute(sa.text("SELECT id FROM userbase LIMIT 1"))
        first_user = result.fetchone()
        if first_user:
            default_user_id = first_user[0]
        else:
            # If no users exist, we can't set a default - skip this migration
            return
    
    # Update NULL user_id values to the default user
    conn.execute(sa.text("UPDATE lostandfounditem SET user_id = :user_id WHERE user_id IS NULL"), 
                 {"user_id": default_user_id})
    conn.execute(sa.text("UPDATE prayerrequest SET user_id = :user_id WHERE user_id IS NULL"), 
                 {"user_id": default_user_id})
    
    # Now make the columns NOT NULL using batch_alter_table for SQLite compatibility
    with op.batch_alter_table('lostandfounditem', schema=None) as batch_op:
        batch_op.alter_column('user_id',
                   existing_type=sa.INTEGER(),
                   nullable=False)
    
    with op.batch_alter_table('prayerrequest', schema=None) as batch_op:
        batch_op.alter_column('user_id',
                   existing_type=sa.INTEGER(),
                   nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prayerrequest', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('lostandfounditem', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('_alembic_tmp_lostandfounditem',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('category', sa.VARCHAR(), nullable=False),
    sa.Column('contact', sa.VARCHAR(), nullable=False),
    sa.Column('location_found', sa.VARCHAR(), nullable=False),
    sa.Column('date_found', sa.DATETIME(), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=2048), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['userbase.id'], name=op.f('fk_lostandfounditem_user')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
