"""Made some model changes

Revision ID: 377230e30d1e
Revises: ded9d6cda070
Create Date: 2025-12-17 17:57:23.096042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '377230e30d1e'
down_revision: Union[str, Sequence[str], None] = 'ded9d6cda070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lostandfounditem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location_found', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_found', sa.DateTime(), nullable=False),
    sa.Column('image_url', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userbase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('major', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('graduation_year', sa.Integer(), nullable=False),
    sa.Column('profile_image_url', sa.String(length=2048), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prayerinteractionmodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prayer_request_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('interaction_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prayer_request_id'], ['prayerrequest.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['userbase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roommateprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('preferences', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('housing_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sleep_schedule', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('looking_for', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['userbase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    op.drop_table('lostitem')
    op.drop_column('prayerrequest', 'posted_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prayerrequest', sa.Column('posted_by', sa.VARCHAR(), nullable=False))
    op.create_table('lostitem',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('location_found', sa.VARCHAR(), nullable=False),
    sa.Column('contact', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.Column('major', sa.VARCHAR(), nullable=False),
    sa.Column('graduation_year', sa.INTEGER(), nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), server_default=sa.text('(false)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('roommateprofile')
    op.drop_table('prayerinteractionmodel')
    op.drop_table('userbase')
    op.drop_table('lostandfounditem')
    # ### end Alembic commands ###
