"""Tie user to the posts

Revision ID: 42d0880e871d
Revises: a52304c4ad30
Create Date: 2025-12-30 22:49:32.797748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '42d0880e871d'
down_revision: Union[str, Sequence[str], None] = 'a52304c4ad30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lostandfounditem', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('prayerrequest', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prayerrequest', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('lostandfounditem', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
