"""Lost

Revision ID: 95b409c54f99
Revises: f646e2ae1657
Create Date: 2025-11-28 01:00:28.460604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '95b409c54f99'
down_revision: Union[str, Sequence[str], None] = 'f646e2ae1657'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lostitem', 'date_lost')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lostitem', sa.Column('date_lost', sa.DATETIME(), nullable=False))
    # ### end Alembic commands ###
