"""Added more users

Revision ID: f646e2ae1657
Revises: 3c07ef054ffc
Create Date: 2025-11-07 12:28:48.359982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f646e2ae1657'
down_revision: Union[str, Sequence[str], None] = '3c07ef054ffc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'major',
               existing_type=sa.String(),
               nullable=False)
    op.alter_column('user', 'graduation_year',
               existing_type=sa.Integer(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'graduation_year',
               existing_type=sa.String(),
               nullable=True)
    op.alter_column('user', 'major',
               existing_type=sa.Integer(),
               nullable=True)
    # ### end Alembic commands ###
